apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: greepapptemplates.app.greep.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: app.greep.io
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                serviceName:
                  type: string
                environment:
                  type: string
                deploymentReplicas:
                  type: integer
                  maximum: 5
                  default: 1
                imageVersion:
                  type: string
                letEncryptEmail:
                  type: string
                  default: "ayo@greep.io"
                configsToUse:
                  type: string
                  default: ""
                httpsDomain1:
                  type: string
                  default: ""
                httpsDomain2:
                  type: string
                  default: ""
                httpsDomain3:
                  type: string
                  default: ""
                httpsDomain4:
                  type: string
                  default: ""
                websocketDomain:
                  type: string
                  default: ""
                wildcardDomain1:
                  type: string
                  default: ""
                wildcardDomain2:
                  type: string
                  default: ""

  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: greepapptemplates
    # singular name to be used as an alias on the CLI and for display
    singular: greepapptemplate
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: GreepAppTemplate
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
      - greepapp
