apiVersion: v1
kind: ConfigMap
metadata:
  name: greep-app-template-config
  namespace: default
data:
  # your custom resource groupname
  RESOURCE_GROUP: "app.greep.io"

  # your custom resource name (plural)
  RESOURCE_NAME: "greepapptemplates"

  # default api version of your custom resource
  API_VERSION: "v1"

  # default docker container registry
  DOCKER_REGISTRY: "greep.azurecr.io"

  # default custom resource namespace
  RESOURCE_NAMESPACE: "default"

  # git repo url for template config files
  CONFIG_REPO_URL: "https://github.com/GreepPay/GreepTemplateConfigs.git"

  # repo sync interval (in seconds)
  SYNC_INTERVAL: "5"
